from pathlib import Path


MAP_WIDTH = 900
UI_WIDTH = 280
WIDTH, HEIGHT = MAP_WIDTH + UI_WIDTH, 600

BASE_DIR = Path(__file__).resolve().parents[1]
ASSET_DIR = BASE_DIR / "assets"

BUILD_TILE_SIZE = 54
BUILD_GRID_STEP = 27
BUILD_GRID_TOP = 81
PATH_WIDTH = 54
BUILD_PATH_PADDING = 0
BASE_TOWER_RANGE = 145
RENDERER = "pygame"
ENABLE_GLOW = True
ENABLE_PARTICLES = True
ENABLE_SCREEN_SHAKE = True
MAX_PARTICLES = 450

MAX_WAVE = 30
STARTING_MONEY = 175
STARTING_LIVES = 25
BASE_ENEMIES_PER_WAVE = 10
ENEMIES_PER_WAVE_GROWTH = 3
MIN_SPAWN_INTERVAL = 0.18
START_WAVE_BONUS = 10

MAX_ACTIVE_ENEMIES = 260
MAX_SPLIT_CHILDREN = 150
MAX_ACTIVE_PROJECTILES = 220
MAX_ACTIVE_EFFECTS = 110
MAX_FLOATING_TEXTS = 24
BUSY_ENEMY_COUNT = 90
VERY_BUSY_ENEMY_COUNT = 180
CROWD_HEALTH_BAR_LIMIT = 95
MUTATION_SLOT_LIMIT = 2
CORRUPTION_DEATH_RADIUS = 120

BASE_MAX_TOWER_LEVEL = 5
MAX_TOWER_LEVEL = 10
PARAGON_LEVEL = 6
TOWER_COST = 50
SELL_REFUND_RATE = 0.75
PARAGON_SELL_REFUND_RATE = 0.5
